module ApplicationHelper
  def recipe_category_options
    [
      "Appetizers & Snacks",
      "Beverages",
      "Breakfast & Brunch",
      "Breads & Baking",
      "Cakes & Cupcakes",
      "Candies & Confections",
      "Casseroles",
      "Condiments & Preserves",
      "Cookies & Bars",
      "Desserts",
      "Dips & Spreads",
      "Grilling & BBQ",
      "Ice Cream & Frozen Treats",
      "Main Dishes",
      "Marinades & Rubs",
      "Pasta & Noodles",
      "Pies & Tarts",
      "Pizza",
      "Salads",
      "Sandwiches & Wraps",
      "Sauces & Seasonings",
      "Seafood",
      "Side Dishes",
      "Slow Cooker",
      "Smoothies & Shakes",
      "Soups & Stews",
      "Vegetarian & Vegan"
    ]
  end

  def recipe_cuisine_options
    [
      "African",
      "American",
      "Argentinian",
      "Asian Fusion",
      "Australian",
      "Austrian",
      "Belgian",
      "Brazilian",
      "British",
      "Cajun",
      "Caribbean",
      "Chinese",
      "Colombian",
      "Cuban",
      "Czech",
      "Ethiopian",
      "French",
      "German",
      "Greek",
      "Hungarian",
      "Indian",
      "Indonesian",
      "Irish",
      "Italian",
      "Japanese",
      "Jewish",
      "Korean",
      "Lebanese",
      "Malaysian",
      "Mediterranean",
      "Mexican",
      "Middle Eastern",
      "Moroccan",
      "Peruvian",
      "Polish",
      "Portuguese",
      "Russian",
      "Scandinavian",
      "Southern",
      "Spanish",
      "Swedish",
      "Thai",
      "Turkish",
      "Ukrainian",
      "Vietnamese",
      "Other"
    ]
  end
end