module ApplicationHelper
  def recipe_category_options
    [
      "Breakfast",
      "Brunch",
      "Lunch",
      "Beverages",
      "Appetizers",
      "Soup & Stews",
      "Salads / Vegetable",
      "Salads / Dessert",
      "Main Dishes / Beef",
      "Main Dishes / Poultry",
      "Main Dishes / Pork",
      "Main Dishes / Seafood",
      "Main Dishes / Vegetarian",
      "Main Dishes / Other",
      "Side Dishes / Vegetables",
      "Side Dishes / Grain",
      "Side Dishes / Other",
      "Condiments",
      "Sauces",
      "Desserts / Seasoning",
      "Desserts / Cookies",
      "Desserts / Bars",
      "Desserts / Cakes & Frosting",
      "Desserts / Pies",
      "Desserts / Candy",
      "Desserts / Sauces",
      "Bread / Quick",
      "Bread / Yeast"
    ]
  end

  def recipe_cuisine_options
    [
      "African",
      "American",
      "Argentinian",
      "Australian",
      "Austrian",
      "Belgian",
      "Brazilian",
      "British",
      "Cajun",
      "Caribbean",
      "Chinese",
      "Colombian",
      "Cuban",
      "Czech",
      "Ethiopian",
      "French",
      "German",
      "Greek",
      "Hungarian",
      "Indian",
      "Indonesian",
      "Irish",
      "Italian",
      "Japanese",
      "Jewish",
      "Korean",
      "Lebanese",
      "Malaysian",
      "Mediterranean",
      "Mexican",
      "Middle Eastern",
      "Moroccan",
      "Peruvian",
      "Polish",
      "Portuguese",
      "Russian",
      "Scandinavian",
      "Southern",
      "Spanish",
      "Swedish",
      "Thai",
      "Turkish",
      "Ukrainian",
      "Vietnamese",
      "Other"
    ]
  end
end
